README.md
=> Add 'npm install' instruction under 'Get started'

src/config/conf.js, src/utils.js
=> logging Selenium Grid info to console

CHANGELOG.md, package.json, src/plugins/reporter/aggregate.js, src/plugins/reporter/index.js
=> Fix Reporting in parallel test execution

CHANGELOG.md, bin/aw-webdriver-test-runner.js, docs/e2e.md, package.json, src/browser/browser-test-runner.js, src/config/conf.dev.js, src/config/conf.js
=> Remove protractor

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
* [ x] Waiting for code review
=> Change issue template from checkboxes to code snippet

src/plugins/reporter/aggregate.js, src/plugins/reporter/utils.js, src/utils.js
Protractor Tests
Add selenium grid extra information, where test is executed and the url for the video.
After aggregating test results return them to the caller.
```
[x] Waiting for code review
```
```
[x] Contains new API(s)
```
```
[x] Fix lint error "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style"
```
=> Add Selenium Grid Extra Infos

README.md
This closes #18.
```
[X] Waiting for code review
```
=> Add circle ci badge to readme

.circleci/config.yml
This closes #31.
```
[x] Waiting for code review
```
=> Use greenkeeper-lockfile to update package-lock.json for GK branches

.circleci/config.yml, README.md, package-lock.json, package.json
```
[x] Waiting for code review
[x] Waiting for merge
```
=> Adds coveralls to AW.js

src/plugins/screenshoter/utils.js
```
[x] Waiting for code review
```
```
```
```
[ ] ...
```
=> Adjust matchImageOf to async-await

package-lock.json, package.json
```
```
```
```
```
[ ] ...
```
=> Greenkeeper/globby 7.1.1

src/node/options.js
This reverts commit 78f1b4a2d487ba9d558b6326f296e63cccad6181.
=> Revert "NODE - default exclude test files"

package-lock.json, package.json
```
```
```
```
```
[ ] ...
```
=> Greenkeeper/moment 2.20.1

src/node/index.js
Ensure not to crash when changing src files
=> NODE - safer watch mode

src/cdp/runner.js
Ensure normalizing require paths else it will break on windows
=> CDP - normalize paths

package-lock.json, package.json
```
```
```
```
```
[ ] ...
```
=> Greenkeeper/chrome launcher 0.10.2

src/protractor/index.js
This ensures extending the config with passed argv object
=> fix(protractor): extend config with argv

package-lock.json, package.json
```
```
```
```
```
[ ] ...
```
=> Greenkeeper/sinon 4.2.2

package-lock.json, package.json
Fixes #166 
```
```
```
```
```
[ ] ...
```
=> Greenkeeper/sinon 4.4.2

package-lock.json, package.json
```
```
```
```
```
[ ] ...
```
=> Greenkeeper/sinon 5.0.3

src/protractor/plugins/reporter/index.js, src/protractor/plugins/screenshoter/utils.js
Fixes #203 .
```
[x ] Waiting for code review
```
```
Circle
```
=> Fix JSON parse for reporting

src/protractor/plugins/screenshoter/utils.js
```
```
```
```
```
[ ] ...
```
=> Adding jSON.parse to assert message

test/unit/node/index.spec.js, test/unit/protractor/plugins/reporter/create-static.spec.js, test/unit/protractor/plugins/reporter/index.spec.js, test/unit/protractor/plugins/reporter/utils.spec.js, test/unit/protractor/plugins/screenshoter/index.spec.js, test/unit/protractor/plugins/screenshoter/utils.spec.js
```
```
```
```
```
[ ] ...
```
=> Fix deprecation of sinon.sandbox.create()

website/blog/2018-09-12-react-aw.md
=> docs: baby step by step guide

examples/react/src/state-hook-example.jsx, examples/react/test/state-hook-example.spec.jsx
Adding an example of testing with a React state hook.
=> test: add state hook example

commands/node/src/index.js
Try find spec files from base names
Also if a React component is used check
first character lower case
=> feat: better watch

packages/register/src/globals.d.ts
Need to rename to `globals.d.ts`
=> chore: fix typings

commands/puppeteer/package.json, commands/puppeteer/src/index.js, commands/puppeteer/src/options.js, examples/puppeteer/test/hello.fix.html, plugins/interactive-plugin/src/index.js, yarn.lock
Support generating screenshots on failing `puppeteer` tests. You can also dump it in the terminal if you like.
=> feat(puppet): dump screenshots on failing test

yarn.lock
Updating all the deps and seeing how the build reacts, this deals with tons of security issues we have open on the project.
=> build: yarn upgrade

website/yarn.lock
`yarn upgrade` for the website/ dir
=> chore: yarn upgrade for website/

commands/protractor/test/unit/plugins/reporter/utils.spec.js, examples/node-js-no-babel/test/index.spec.js, package.json, yarn.lock
Includes lint fixes from this update
=> build(deps): update eslint-config-airbnb to 18.2.0

packages/utils/src/index.js
Same as https://github.com/qlik-oss/after-work.js/pull/535 but for master
=> fix: support nohoist in yarn workspaces
